# fly.toml file generated for pleromav2 on 2022-12-01T09:00:22-07:00

app = "pleromav2"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "jtomchak/fly-pleroma:v2.4.4"

[env]
  PLEROMA_CONFIG_PATH = "/mount/config/config.exs"
  START_PLEROMA = "1"

[mounts]
  source = "pleroma_storage"
  destination = "/mount"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
